# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1daSmAaLf7kc-hXJVHr31t4XWTZMUk_4D
"""

from google.colab import drive
drive.mount('/content/drive')

pip install ultralytics

from matplotlib import pyplot as plt
import numpy as np
import cv2

from ultralytics import YOLO

# Modelni yuklash (masalan, yolov8n.pt - 'nano' versiyasi, eng kichik va tezkor)
model = YOLO('yolov8n.pt')  # Modelning kichikroq versiyasini yuklaydi, masalan, nano versiyasi

from ultralytics import YOLO

# YOLO modelini yuklash (agar avval yuklanmagan bo'lsa)
# Bu qadamni takrorlamaslik uchun 'model' o'zgaruvchisi mavjudligini tekshiramiz.
if 'model' not in globals():
    model = YOLO('yolov8n.pt') # 'nano' versiyasi, eng kichik va tezkor

import os

# Lokal rasmni aniqlash
local_image_path_user = '/content/for yolo.jpg'

# Rasmdagi obyektlarni aniqlash
# `source`ga fayl yo'lini beramiz
results_user_local = model.predict(source=local_image_path_user, save=True, conf=0.5)

# Natijalarni ko'rsatish
print("Aniqlash natijalari (foydalanuvchi rasmi):")
for r in results_user_local:
    print(f"  BBox koordinatalari: {r.boxes.xyxy}")
    print(f"  Ishonch ballari: {r.boxes.conf}")
    print(f"  Sinf raqamlari: {r.boxes.cls}")

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

# `results_user_local` obyektidan saqlangan rasmning to'liq yo'lini olamiz
if results_user_local and len(results_user_local) > 0:
    save_directory_user_local = results_user_local[0].save_dir
    original_image_name_user_local = os.path.basename(results_user_local[0].path)
    image_path_to_display_user_local = os.path.join(save_directory_user_local, original_image_name_user_local)

    if os.path.exists(image_path_to_display_user_local):
        img_user_local = mpimg.imread(image_path_to_display_user_local)
        plt.figure(figsize=(12, 10))
        plt.imshow(img_user_local)
        plt.axis('off')
        plt.title(f'Aniqlangan obyektlar bilan rasm: {original_image_name_user_local}')
        plt.show()
    else:
        print(f"Aniqlangan rasm topilmadi: {image_path_to_display_user_local}")
else:
    print("Hech qanday natija topilmadi.")

from ultralytics import YOLO

# YOLO modelini yuklash (agar avval yuklanmagan bo'lsa)
# Bu qadamni takrorlamaslik uchun 'model' o'zgaruvchisi mavjudligini tekshiramiz.
if 'model' not in globals():
    model = YOLO('yolov8n.pt') # 'nano' versiyasi, eng kichik va tezkor

# Internetdan boshqa bir rasmni yuklash va aniqlash (masalan, ultralytics.com/images/bus.jpg)
# Bu safar 'bus.jpg' emas, balki boshqa bir mashhur rasm, masalan, 'bus.jpg' ni ishlatsak ham bo'ladi.
# Hozirda mavjud bus.jpg ni ishlata olamiz yoki yangi URL beramiz.
# Keling, buni /content/bus.jpg bilan qayta ishlatsak. Sizda bu rasm allaqachon mavjud edi.
# Agar siz boshqa rasmni xohlasangiz, url qismini o'zgartirishingiz mumkin.
# Masalan: source='https://ultralytics.com/images/bus.jpg'

results_another = model.predict(source='https://ultralytics.com/images/bus.jpg', save=True, conf=0.5)

# Natijalarni ko'rsatish
print("Aniqlash natijalari (yangi rasm):")
for r in results_another:
    print(f"  BBox koordinatalari: {r.boxes.xyxy}")
    print(f"  Ishonch ballari: {r.boxes.conf}")
    print(f"  Sinf raqamlari: {r.boxes.cls}")

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

# `results_another` obyektidan saqlangan rasmning to'liq yo'lini olamiz
if results_another and len(results_another) > 0:
    save_directory_another = results_another[0].save_dir
    original_image_name_another = os.path.basename(results_another[0].path)
    image_path_another = os.path.join(save_directory_another, original_image_name_another)
else:
    image_path_another = None # Agar natijalar topilmasa, yo'lni bo'sh qoldiramiz

# Rasmni o'qish va ko'rsatish
if image_path_another and os.path.exists(image_path_another):
    img_another = mpimg.imread(image_path_another)
    plt.figure(figsize=(12, 10))
    plt.imshow(img_another)
    plt.axis('off')
    plt.title(f'Aniqlangan obyektlar bilan rasm: {original_image_name_another}')
    plt.show()
else:
    print(f"Aniqlangan rasm topilmadi: {image_path_another}")

import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
from ultralytics import YOLO

# YOLO modelini yuklash (agar avval yuklanmagan bo'lsa)
# Agar 'model' o'zgaruvchisi allaqachon mavjud bo'lsa, bu qadamni o'tkazib yuborish mumkin.
if 'model' not in globals():
    model = YOLO('yolov8n.pt') # 'nano' versiyasi, eng kichik va tezkor

# Lokal rasmni yuklash (masalan, /content/bus.jpg)
local_image_path = '/content/bus.jpg'

# Rasmdagi obyektlarni aniqlash
# `source`ga fayl yo'lini beramiz
results_local = model.predict(source=local_image_path, save=True, conf=0.5)

# Natijalarni ko'rsatish
print("Aniqlash natijalari:")
for r in results_local:
    print(f"  BBox koordinatalari: {r.boxes.xyxy}")
    print(f"  Ishonch ballari: {r.boxes.conf}")
    print(f"  Sinf raqamlari: {r.boxes.cls}")

# Aniqlangan obyektlar bilan rasmni ko'rsatish
if results_local and len(results_local) > 0:
    save_directory_local = results_local[0].save_dir
    original_image_name_local = os.path.basename(results_local[0].path)
    image_path_to_display = os.path.join(save_directory_local, original_image_name_local)

    if os.path.exists(image_path_to_display):
        img_local = mpimg.imread(image_path_to_display)
        plt.figure(figsize=(12, 10))
        plt.imshow(img_local)
        plt.axis('off')
        plt.title(f'Aniqlangan obyektlar bilan rasm: {original_image_name_local}')
        plt.show()
    else:
        print(f"Aniqlangan rasm topilmadi: {image_path_to_display}")
else:
    print("Hech qanday natija topilmadi.")

"""YOLOv8 modelidan foydalanish uchun `ultralytics` kutubxonasini import qilamiz va modelni yuklaymiz. Keyin rasmdagi obyektlarni aniqlash uchun `predict` funksiyasidan foydalanishimiz mumkin."""

from ultralytics import YOLO

# Modelni yuklash (masalan, yolov8n.pt - 'nano' versiyasi, eng kichik va tezkor)
model = YOLO('yolov8n.pt')  # Modelning kichikroq versiyasini yuklaydi, masalan, nano versiyasi

# Namuna rasmidagi obyektlarni aniqlash
# predict metodiga rasm yo'lini berishingiz mumkin
# Yangi rasm: yo'lbars
results = model.predict(source='https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg', save=True, conf=0.5)

# Natijalarni ko'rsatish (aniqlangan obyektlar bilan birga rasm saqlanadi)
for r in results:
    print(r.boxes.xyxy)  # Aniqlangan obyektlarning chegaralovchi qutilarini ko'rsatish (koordinatalar)
    print(r.boxes.conf)  # Har bir obyekt uchun ishonch ballarini ko'rsatish
    print(r.boxes.cls)   # Har bir obyektning sinf raqamini ko'rsatish